# fly.toml app configuration file for discordbotjs
# This configuration is for a background worker that doesn't expose HTTP/TCP services.

app = 'discordbotjs'
primary_region = 'dfw' # Or your chosen region

[build]
  dockerfile = "Dockerfile"

# Defines the 'app' process that runs your Docker CMD
# For workers, you might not need a [[services]] block if you don't need health checks on a port.
# We will manage the number of running machines using `fly scale count`.
[processes]
  app = "" # Uses Dockerfile's CMD (node index.js)

# VM Configuration for the free tier
[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256 # Explicitly define 256MB RAM

